async (page) => {
  const checks = [];
  const assert = (ok, name) => { if (!ok) throw new Error(name); checks.push(name); };
  const field = id => page.locator(`[data-field="${id}"]`);
  const state = () => page.evaluate(()=>JSON.parse(localStorage.getItem('moss-prefill-form:v2')).state);
  const saved = async id => (await state()).fields.find(f=>f.id===id);
  const reset = async () => { await page.getByRole('button', {name:'重置演示数据',exact:true}).click(); };
  await page.setViewportSize({width:1920,height:1080});
  await page.goto('http://127.0.0.1:5173/'); await reset(); await page.evaluate(()=>document.fonts.ready);
  assert((await page.locator('[data-field]').evaluateAll(els=>els.map(el=>el.getAttribute('data-field')))).join(',') === 'location,caller,callback,reason,ongoing,people,injury,equipment,description', '九字段顺序');
  assert(await page.locator('.inline-confirm').count() === 2, '只有两项强确认');
  assert((await page.locator('.inline-confirm').allTextContents()).every(text=>text==='确认'), '按钮文字均为确认');
  assert(await page.locator('.ai-mark').count() === 9, '初始AI来源标识');
  assert(await page.locator('.field-hint').count()===0, '默认无字段提示');
  await page.getByRole('button',{name:'移交调度',exact:true}).click();
  assert(await page.locator('.field-hint').count()===2 && await page.getByRole('alertdialog').count()===0, '未确认提交只显示两项原因');
  await reset();
  assert(await page.locator('.form-column').evaluate(el=>el.scrollHeight<=el.clientHeight+1), '1920下全部初始字段可见');
  assert(await field('caller').evaluate(el=>{ const icon=el.querySelector('.ai-mark').getBoundingClientRect(); const input=el.querySelector('input').getBoundingClientRect();return icon.left<input.left+40 && Math.abs(icon.y+icon.height/2-input.y-input.height/2)<2; }), '标识在输入框左侧单行居中');
  const caller=page.getByRole('textbox',{name:'报警人',exact:true});
  const people=page.getByRole('textbox',{name:'参与人数',exact:true});
  const callback=page.getByRole('textbox',{name:'回拨号码',exact:true});
  const address=page.getByRole('combobox',{name:'事发地点',exact:true});
  await caller.click(); await people.click();
  assert((await saved('caller')).origin==='ai', '未修改失焦保留AI');
  await caller.fill('李'); await caller.fill('陈（自述姓氏）'); await people.click();
  assert(await field('caller').locator('.ai-mark').count()===1 && (await saved('caller')).history.length===0, '改回原值失焦保留AI且无虚假记录');
  await caller.fill('李（自述姓氏）'); await people.click();
  assert((await saved('caller')).value==='李（自述姓氏）' && (await saved('caller')).draft===null, '失焦自动保存');
  assert(await field('caller').locator('.field-status').getAttribute('aria-label')==='人工修改，待发送时确认', '保存后人形修改图标');
  assert(await page.locator('.edit-toolbar').count()===0 && await page.getByRole('button',{name:'应用修改',exact:true}).count()===0, '无应用修改操作条');
  await people.fill('3人'); await people.press('Escape'); await caller.click();
  assert(await people.inputValue()==='2人' && (await saved('people')).origin==='ai', '失焦前Esc撤销编辑');
  await page.getByRole('combobox',{name:'事件是否持续',exact:true}).click();
  await page.getByRole('option',{name:'否',exact:true}).click();
  await page.waitForFunction(()=>JSON.parse(localStorage.getItem('moss-prefill-form:v2')).state.fields.find(f=>f.id==='ongoing').draft===null);
  assert((await saved('ongoing')).value==='否' && (await saved('ongoing')).origin==='manual', '下拉选项关闭即保存，显示人工修改');
  await page.getByRole('button',{name:'确认地点',exact:true}).click();
  await address.click(); await address.fill('安和');
  assert(await page.getByRole('option').count()===12, '地点关键词匹配及12个关联选项');
  await page.getByRole('option').filter({hasText:'安和广场西门'}).click();
  assert((await address.inputValue()).includes('西门'), '鼠标选候选不因失焦丢失点击');
  await caller.click();
  assert((await saved('location')).origin==='manual' && (await saved('location')).review==='modified', '选中候选自动保存并确认');
  assert(await page.getByRole('button',{name:'确认地点',exact:true}).count()===0, '选中候选不需要二次确认');
  assert((await saved('location')).review==='modified', '候选选择后的确认状态正确');
  await page.getByRole('button',{name:'确认号码',exact:true}).click();
  await callback.fill('139****6721');
  await page.getByRole('button',{name:'确认号码',exact:true}).click();
  assert((await saved('callback')).value==='139****6721' && (await saved('callback')).review==='modified', '从输入直接点确认，失焦保存不吞按钮点击');
  await callback.fill(''); await caller.click();
  assert(await field('callback').getByRole('alert').isVisible(), '空值自动保存失败提示并保留草稿');
  await callback.click(); await callback.press('Escape'); await caller.click();
  assert((await saved('callback')).value==='139****6721' && (await saved('callback')).draft===null, '空值错误可Esc恢复');
  await people.fill('3人'); await caller.click();
  await page.getByRole('button',{name:'模拟新原话'}).click();
  assert(await people.inputValue()==='3人', '失焦保存的人工值不被新原话覆盖');
  await page.getByRole('button',{name:'移交调度',exact:true}).click();
  assert(await field('people').getByRole('alert').isVisible() && await page.getByRole('alertdialog').count()===0, '提交遇待核对项在字段右上角说明原因');
  await page.getByRole('region',{name:'参与人数的新信息'}).getByRole('button',{name:'保留当前值'}).click();
  assert(await field('people').getByRole('alert').count()===0, '处理后原因自动消失');
  await people.fill('5人'); await page.getByRole('button',{name:'移交调度',exact:true}).click();
  assert((await state()).sent?.values.people==='5人' && await page.getByRole('alertdialog').count()===0, '直接提交先保存活动输入且无二次弹窗');
  assert(await page.locator('.tone-confirmed').count()===9 && await page.locator('.field-status svg').count()===9, '整体确认保留九个人形标识');
  await page.reload();
  assert((await saved('caller')).value==='李（自述姓氏）' && (await saved('callback')).value==='139****6721', '刷新恢复失焦保存结果');
  await page.screenshot({path:'/Users/hpl/Documents/ChatGPT/客服预填单/form-demo/screenshot-confirmed.png',fullPage:true});
  await reset();
  assert((await state()).sent===null && (await state()).fields.every(f=>f.review==='pending'&&f.history.length===0), '重置恢复初始值、核对状态与记录');
  await address.click(); await page.screenshot({path:'/Users/hpl/Documents/ChatGPT/客服预填单/form-demo/screenshot-location.png',fullPage:true});
  await address.press('Escape'); await page.locator('#form-title').click();
  await page.screenshot({path:'/Users/hpl/Documents/ChatGPT/客服预填单/form-demo/screenshot-initial.png',fullPage:true});
  return {passed:checks.length,checks};
}
